---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: hardware-inventory
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  .dockerconfigjson: |-
    <PULL_SECRET | base64encode>
type: kubernetes.io/dockerconfigjson
