---
apiVersion: v1
kind: Secret
metadata:
  name: hosted-worker2-bmc-secret
  namespace: hardware-inventory
data:
  password: <BMC_PASSWORD | base64encode>
  username: <BMC_USERNAME | base64encode>
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: hosted-worker2
  namespace: hardware-inventory
  labels:
    infraenvs.agent-install.openshift.io: bare-metal
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: worker-2
spec:
  automatedCleaningMode: metadata
  bmc:
    disableCertificateVerification: True
    address: redfish-virtualmedia+http://172.23.3.24:8000/redfish/v1/Systems/578bda9d-b845-4732-b756-ce608cdaeb60
    credentialsName: worker-2-bmc-secret
  bootMACAddress: '52:54:00:22:4d:5a'
  online: true
  rootDeviceHints:
    deviceName: /dev/vda
