---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: venafi-issuer
spec:
  venafi:
    zone: \Policy\Certificates\Internal\Openshift
    tpp:
      url: https://venafi.example.com
      caBundle: '{{ fromConfigMap "openshift-config" "user-ca-bundle" "ca-bundle.crt" | base64enc }}'
      credentialsRef:
        name: venafi-access
---
kind: Secret
apiVersion: v1
metadata:
  name: venafi-access
  namespace: cert-manager
data:
  access-token: '{{hub fromSecret "" "venafi-access" "access-token" hub}}'
type: Opaque
