apiVersion: v1
kind: Secret
metadata:
    name: sops-secret-message
    namespace: a-team
type: Opaque
stringData:
    message: Hello there from Will!
sops:
    age:
        - recipient: age1k0p7ppfv84zlpemvpya269upa5pvmxwvw54a0frud4acd2szfpwslttgxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK3dvazBhSmxSSW8wQW1U
            SHVMN1FYM2swUDcxOXMvMHE3SjduRnZXZjJrCnI5bGd1R1dXcW40RlpBcVVRaitR
            Y25FRjliWWJEakpHbjVORm5oMEhxR2sKLS0tIHRpb3dWUzZWbWFjY1E1VGlOa1E2
            RDF4TklDWnJQdDh6RVdWbGZuOXhqbXcKyfoWudE5L2zlgUOmaJyLIjJtAPSQh0MD
            REJhM4IUIkjS0XyXB4JDtpsvfX2jXej65qgQxpsjof1zG+VXHZne1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T05:22:20Z"
    mac: ENC[AES256_GCM,data:T2vr09IjrGS8TtHDmBAwQ0qXY84z155ItVuAsleA6ODpk/Sw/YM1THhyuPr66Vqum3e8o//qs5yIzLR0vyd9RcwvBuUfIoueLBbEsAdq/7n08seLzxDmm/AsvTeljdWZ2e27xgpRZKzTa00ZWkN/q1NT0ftzLCoPtQJOpigCMNQ=,iv:NDftdUmc9VYJc1KFQNOgvsyP4eeJW6Zbx0zugCOrGk4=,tag:K9IzpP2F6UAaUaCqd8j56g==,type:str]
    encrypted_regex: ^(stringData\.message)$
    version: 3.10.2
