---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: openshift-gitops
spec:
  generators:
  - clusters: {} 
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: metallb
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops
      source:
        repoURL: https://github.com/wcushen/acm-sno-lab.git
        path: gitops/applications/metallb/overlay/mce
        plugin:
          name: kustomize-novault-plugin
        targetRevision: feature/sans-acm
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - Validate=true