---
apiVersion: v1
kind: Secret
metadata:
  name: worker-3-bmc-secret
  namespace: hardware-inventory
data:
  password: <BMC_PASSWORD | base64encode>
  username: <BMC_USERNAME | base64encode>
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker-3
  namespace: hardware-inventory
  labels:
    infraenvs.agent-install.openshift.io: hosted
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: worker-3
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    disableCertificateVerification: True
    address: redfish-virtualmedia+http://172.23.3.24:8000/redfish/v1/Systems/948b43c9-967b-43bc-98d4-08da9509ee53
    credentialsName: worker-3-bmc-secret
  bootMACAddress: '52:54:00:22:4d:5b'
  online: true
