---
apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JFpnWHNISHEwbTlYVHN2SUhLdnR4SmV5OUpWaUhCZ1h6ZUQ4alg1RFhvOEFsaVcwcDBSVldLCg==
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque