---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multicluster-engine
  namespace: multicluster-engine
spec:
  availabilityConfig: Basic
  overrides:
    components:
    - enabled: true # false
      name: local-cluster
    - enabled: true # false
      name: hypershift-local-hosting
