---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: registry
  namespace: quay
spec:
  configBundleSecret: init-config-bundle-secret
  components:
    - kind: clairpostgres
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: monitoring
      managed: true
    - kind: objectstorage
      managed: true
    - kind: postgres
      managed: true
    - kind: redis
      managed: true
    - kind: route
      managed: true
    - kind: tls
      managed: true
    - kind: quay
      managed: true
    - kind: clair
      managed: true
      overrides:
        volumeSize: 100Gi
