apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: cluster
rendezvousIP: 192.168.10.21
hosts:
  - hostname: master1
    interfaces:
      - name: ens1f0
        macAddress: b4:96:91:c1:54:3c
      - name: ens1f1
        macAddress: b4:96:91:c1:54:3d
    networkConfig:
      dns-resolver:
        config:
          server:
          - 172.23.3.254
      routes:
        config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.23.3.254
          next-hop-interface: bond0
          table-id: 254
      interfaces:
        - name: ens1f0
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3c
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f1
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3d
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f0.3
          type: vlan
          state: up
          vlan:
            base-iface: ens1f0
            id: 3
        - name: bond0
          type: bond
          state: up
          link-aggregation:
            mode: active-backup
            options:
              primary: ens1f0.3
            port:
              - ens1f0.3
          ipv4:
            address:
              - ip: 172.23.3.25
                prefix-length: 24
            dhcp: false
            enabled: true
          ipv6:
            enabled: true
            dhcp: false
  - hostname: master2
    interfaces:
      - name: ens1f0
        macAddress: b4:96:91:c1:54:3c
      - name: ens1f1
        macAddress: b4:96:91:c1:54:3d
    networkConfig:
      dns-resolver:
        config:
          server:
          - 172.23.3.254
      routes:
        config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.23.3.254
          next-hop-interface: bond0
          table-id: 254
      interfaces:
        - name: ens1f0
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3c
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f1
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3d
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f0.3
          type: vlan
          state: up
          vlan:
            base-iface: ens1f0
            id: 3
        - name: bond0
          type: bond
          state: up
          link-aggregation:
            mode: active-backup
            options:
              primary: ens1f0.3
            port:
              - ens1f0.3
          ipv4:
            address:
              - ip: 172.23.3.25
                prefix-length: 24
            dhcp: false
            enabled: true
          ipv6:
            enabled: true
            dhcp: false
  - hostname: master3
    interfaces:
      - name: ens1f0
        macAddress: b4:96:91:c1:54:3c
      - name: ens1f1
        macAddress: b4:96:91:c1:54:3d
    networkConfig:
      dns-resolver:
        config:
          server:
          - 172.23.3.254
      routes:
        config:
        - destination: 0.0.0.0/0
          next-hop-address: 172.23.3.254
          next-hop-interface: bond0
          table-id: 254
      interfaces:
        - name: ens1f0
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3c
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f1
          type: ethernet 
          state: up
          mac-address: b4:96:91:c1:54:3d
          ipv4:
            enabled: false
            dhcp: false
          ipv6:
            enabled: false
            dhcp: false
        - name: ens1f0.3
          type: vlan
          state: up
          vlan:
            base-iface: ens1f0
            id: 3
        - name: bond0
          type: bond
          state: up
          link-aggregation:
            mode: active-backup
            options:
              primary: ens1f0.3
            port:
              - ens1f0.3
          ipv4:
            address:
              - ip: 172.23.3.25
                prefix-length: 24
            dhcp: false
            enabled: true
          ipv6:
            enabled: true
            dhcp: false