apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: hcp-1-ap-southeast-2a
  namespace: hosted
spec:
  arch: amd64
  clusterName: hcp-1
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  nodeVolumeDetachTimeout: 0s
  platform:
    aws:
      instanceProfile: hcp-1-worker
      instanceType: m5.large
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: subnet-03ec8d42168d2b7da
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.18.0-rc.0-multi
  replicas: 3
status:
  replicas: 0