---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: mce-config
placementBindingDefaults:
  name: mce-config
policyDefaults:
  placement:
    placementName: placement-mce
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls:
    - CM-2 Baseline Configuration
  consolidateManifests: false
  copyPolicyMetadata: false
  disabled: false
  namespace: openshift-gitops
  pruneObjectBehavior: "None"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: mce-config
    manifests:
      - path: input/
  # - name: hypershift-mce
  #   manifests:
  #     - path: input/managed-cluster-addon.yaml
  #   placement:
  #     placementName: placement-hub-openshift
